name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentations'
    label: 'documentation'
  - title: 'Dependency Updates'
    label: 'dependency'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
